CREATE TABLE `t_check_task` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `orgId` int(11) DEFAULT NULL,
  `plan` varchar(255) DEFAULT NULL COMMENT '计划名称',
  `planId` int(11) DEFAULT NULL,
  `defect` text COMMENT '异常名称',
  `defectId` int(11) DEFAULT NULL,
  `dev` varchar(255) DEFAULT NULL COMMENT '设备名',
  `devId` int(11) DEFAULT NULL,
  `item` varchar(255) DEFAULT NULL COMMENT '维护项',
  `itemId` int(11) DEFAULT NULL COMMENT '点检项ID',
  `userIds` varchar(500) DEFAULT NULL COMMENT '点检人员ID列表',
  `submitUserId` int(11) DEFAULT NULL COMMENT '完成人ID',
  `classes` varchar(255) DEFAULT NULL COMMENT '班次：早班、中班、晚班，每天，每周，每月，半年',
  `level` varchar(255) DEFAULT NULL COMMENT '排序级别',
  `dateYmd` varchar(255) DEFAULT NULL COMMENT '时间戳\r\n 年月日20170512 \r\n年周2017w23 \r\n年月201702\r\n年季2017s0 第一季度 2017s1第一季度\r\n上半年2017hy0\r\n下半年2017hy1',
  `submitTime` timestamp NULL DEFAULT NULL COMMENT '提交时间',
  `img` int(11) DEFAULT NULL COMMENT '拍摄照图片',
  `taskStatus` tinyint(11) DEFAULT '1' COMMENT ' 任务执行状态：0异常|2正常|1未检|3停机未检',
  `rangeMax` decimal(11,2) DEFAULT NULL COMMENT '范围值上限',
  `rangeMin` decimal(11,2) DEFAULT NULL COMMENT '范围值下限',
  `isCopy` tinyint(4) DEFAULT NULL COMMENT '是否抄表1:需要抄表0:不需要抄表',
  `deptId` int(11) DEFAULT NULL COMMENT '异常报送组的Id',
  `record` decimal(11,2) DEFAULT NULL COMMENT '记录值',
  `expiryTime` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '过期时间',
  `workTime` varchar(50) DEFAULT NULL COMMENT '早班8:00-12:00,每周周三 用于显示任务工作时间段',
  `executeTime` timestamp NULL DEFAULT NULL COMMENT '定时任务推送执行时间',
  `executeMsec` bigint(20) DEFAULT NULL COMMENT '定时任务推送执行时间毫秒数',
  `status` int(2) DEFAULT '1' COMMENT '0删除1正常',
  `createdUserId` int(20) DEFAULT NULL COMMENT '创建用户ID',
  `createdTime` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `lastUpdatedUserId` int(20) DEFAULT NULL COMMENT '更新操作用户ID',
  `lastUpdatedTime` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `base` text COMMENT '基准',
  `devAddress` varchar(255) DEFAULT NULL COMMENT '设备地址',
  `categoryName` varchar(255) DEFAULT NULL COMMENT '类别',
  `period` varchar(255) DEFAULT NULL COMMENT '周期',
  `remind` int(1) DEFAULT '0' COMMENT '0 未提醒 ，1 已提醒',
  `planDevId` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `defectId` (`defectId`),
  KEY `devId` (`devId`),
  KEY `status` (`status`),
  KEY `taskStatus` (`taskStatus`),
  KEY `expiryTime` (`expiryTime`),
  KEY `executeTime` (`executeTime`),
  KEY `orgId` (`orgId`),
  KEY `taskRemind` (`status`,`executeTime`,`expiryTime`,`remind`,`taskStatus`),
  KEY `taskOrgId` (`status`,`orgId`,`executeTime`,`planId`),
  KEY `userIds` (`userIds`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=2578157 DEFAULT CHARSET=utf8mb4 COMMENT='点检任务表';



CREATE TABLE `t_base_defect` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `mId` varchar(255) DEFAULT NULL,
  `orgId` int(11) DEFAULT NULL COMMENT '组织机构ID',
  `categoryId` int(11) DEFAULT NULL COMMENT '报修、巡检、点检、告警',
  `devId` int(11) DEFAULT NULL COMMENT '对应设备ID',
  `dev` text NOT NULL,
  `deptId` int(11) NOT NULL DEFAULT '-1' COMMENT '-1所有0@All',
  `loc` text COMMENT '大坐标位置',
  `subLoc` text COMMENT '二级具体坐标位置',
  `sn` text COMMENT '报修设备编号',
  `cmt` text NOT NULL COMMENT '问题描述',
  `vocs` varchar(255) DEFAULT NULL COMMENT '报修语音String[]',
  `imgs` varchar(255) DEFAULT NULL COMMENT '报修图片说明String[]',
  `rfn` varchar(255) NOT NULL COMMENT 'yym+流水号(同一个企业账号唯一)',
  `wx` tinyint(4) DEFAULT '0' COMMENT '微信报修标志',
  `isTop` int(11) DEFAULT '0' COMMENT '是否置顶1是0否',
  `tt` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '置顶日期',
  `isBoard` tinyint(4) DEFAULT '1' COMMENT '是否在看板上显示 默认1显示0不显示',
  `urgent` tinyint(4) DEFAULT NULL COMMENT '是否加急处理默认0不加急1加急',
  `operateStatus` tinyint(4) DEFAULT '10' COMMENT '10待受理\\\\\\\\r\\\\\\\\n11已撤销 \\\\\\\\r\\\\\\\\n12已指派 \\\\\\\\r\\\\\\\\n13已退回14已收回20已受理\\\\\\\\r\\\\\\\\n21待确认 \\\\\\\\r\\\\\\\\n22被拒绝 \\\\\\\\r\\\\\\\\n23已撤销\\\\\\\\r\\\\\\\\n30已修好 \\\\\\\\r\\\\\\\\n31已确认\\\\\\\\r\\\\\\\\n32 已评论\\\\\\\\r\\\\\\\\n40已关闭\\\\\\\\r\\\\\\\\n100已忽略',
  `wjcTypeMode` varchar(255) DEFAULT NULL COMMENT '微监测仪表信息',
  `status` tinyint(2) NOT NULL DEFAULT '1' COMMENT '0删除1正常',
  `createdUserId` int(11) DEFAULT NULL COMMENT '创建用户ID',
  `createdTime` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `lastUpdatedUserId` int(11) DEFAULT NULL,
  `lastUpdatedTime` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `modifyCount` int(11) DEFAULT '0' COMMENT '修改次数',
  `mpId` int(11) DEFAULT NULL COMMENT '维保商Id',
  `mpName` varchar(100) DEFAULT NULL COMMENT '维保商名称',
  `isOut` int(2) DEFAULT NULL COMMENT '是否外，0否1是',
  `orderId` int(11) DEFAULT NULL COMMENT '外派工单Id',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `orgId` (`orgId`),
  KEY `categoryId` (`categoryId`),
  KEY `createdTime` (`createdTime`),
  KEY `isBoard` (`isBoard`),
  KEY `status` (`status`),
  KEY `operateStatus` (`operateStatus`),
  KEY `deptId` (`deptId`) USING BTREE,
  KEY `devId` (`devId`),
  KEY `rfn` (`rfn`),
  KEY `mId` (`mId`),
  KEY `orgCreateTime` (`orgId`,`status`,`createdTime`) USING BTREE,
  KEY `orgOperate` (`orgId`,`status`,`operateStatus`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=2812681 DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='报修(缺陷)单表';


CREATE TABLE `t_base_defect_log` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `defectId` int(11) DEFAULT NULL,
  `operaterId` int(11) DEFAULT '0' COMMENT '操作人ID',
  `operater` varchar(255) DEFAULT '0',
  `orgId` int(11) DEFAULT NULL,
  `parts` text COMMENT '备件库\r\n[{pn:''料号'',name:''名字'', model:''型号'', num:''数量''},..]',
  `vocs` varchar(255) DEFAULT NULL COMMENT '维修语音String[]',
  `imgs` varchar(255) DEFAULT NULL COMMENT '维修图片列表',
  `content` text COMMENT '维修备注内容',
  `operateStatus` tinyint(11) DEFAULT '0' COMMENT '10待受理\r\n11已撤销 \r\n12已指派 \r\n13已退回\r\n20已受理\r\n21待确认 \r\n22被拒绝 \r\n23已撤销\r\n30已修好 \r\n31已确认\r\n32 已评论\r\n40已关闭\r\n100已忽略',
  `status` tinyint(2) NOT NULL DEFAULT '1' COMMENT '0删除1正常\\\\\\\\r\\\\\\\\n',
  `createdUserId` int(11) DEFAULT '0' COMMENT '创建用户ID',
  `createdTime` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `lastUpdatedUserId` int(11) DEFAULT NULL,
  `lastUpdatedTime` timestamp NULL DEFAULT NULL,
  `mpId` int(11) DEFAULT NULL COMMENT '维保商Id',
  `mpName` varchar(100) DEFAULT NULL COMMENT '维保商名称',
  `isOut` int(2) DEFAULT NULL COMMENT '是否外，0否1是',
  `orderId` int(11) DEFAULT NULL COMMENT '外派工单Id',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `defectId` (`defectId`),
  KEY `createdTime` (`createdTime`),
  KEY `operaterId` (`operaterId`),
  KEY `createdUserId` (`createdUserId`),
  KEY `status` (`status`),
  KEY `orgId` (`orgId`)
) ENGINE=InnoDB AUTO_INCREMENT=11122860 DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='报修单操作日志表';

CREATE TABLE `t_base_defect_operate` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `defectId` int(11) NOT NULL,
  `orgId` int(11) NOT NULL,
  `bxUserId` int(11) DEFAULT '0' COMMENT '报修人ID',
  `bxUserName` varchar(255) DEFAULT NULL,
  `bxTime` timestamp NULL DEFAULT NULL,
  `assignUserId` int(11) DEFAULT '0' COMMENT '被指派人ID',
  `assignUserName` varchar(255) DEFAULT NULL,
  `assignTime` timestamp NULL DEFAULT NULL,
  `assignCmt` text,
  `sendBackUserId` int(11) DEFAULT '0' COMMENT '退回人ID',
  `sendBackUserName` varchar(255) DEFAULT NULL,
  `sendBackTime` timestamp NULL DEFAULT NULL,
  `sendBackCmt` text,
  `acceptUserId` int(11) DEFAULT '0' COMMENT '受理人ID',
  `acceptUserName` varchar(255) DEFAULT NULL,
  `acceptTime` timestamp NULL DEFAULT NULL,
  `finishUserId` int(11) DEFAULT '0' COMMENT '完成人ID',
  `finishUserName` varchar(255) DEFAULT NULL,
  `finishTime` timestamp NULL DEFAULT NULL,
  `finishCmt` text,
  `finishParts` text COMMENT '备件库\\\\\\\\r\\\\\\\\n[{pn:''料号'',name:''名字'', model:''型号'', num:''数量''},..]',
  `newCancelUserId` int(11) DEFAULT '0' COMMENT '新报修撤销人ID',
  `newCancelUserName` varchar(255) DEFAULT NULL,
  `newCancelTime` timestamp NULL DEFAULT NULL,
  `newCancelCmt` text,
  `acceptCancelUserId` int(11) DEFAULT '0' COMMENT '已受理撤销人ID',
  `acceptCancelUserName` varchar(255) DEFAULT NULL,
  `acceptCancelTime` timestamp NULL DEFAULT NULL,
  `acceptCancelCmt` text,
  `confirmUserId` int(11) DEFAULT '0' COMMENT '确认人ID',
  `confirmUserName` varchar(255) DEFAULT NULL,
  `confirmTime` timestamp NULL DEFAULT NULL,
  `commitedUserId` int(11) DEFAULT '0' COMMENT '评论人ID',
  `commitedUserName` varchar(255) DEFAULT NULL,
  `commitedTime` timestamp NULL DEFAULT NULL,
  `commitedCmt` text,
  `operateStatus` tinyint(11) DEFAULT '0' COMMENT '10待受理\r\n11已撤销 \r\n12已指派 \r\n13已退回\r\n20已受理\r\n21待确认 \r\n22被拒绝 \r\n23已撤销\r\n30已修好 \r\n31已确认\r\n32 已评论\r\n40已关闭\r\n100已忽略',
  `status` tinyint(2) NOT NULL DEFAULT '1' COMMENT '0删除1正常\\\\\\\\\\\\\\\\r\\\\\\\\\\\\\\\\n',
  `createdUserId` int(11) DEFAULT '0' COMMENT '创建用户ID',
  `createdTime` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `lastUpdatedUserId` int(11) DEFAULT NULL,
  `lastUpdatedTime` timestamp NULL DEFAULT NULL,
  `mpId` int(11) DEFAULT NULL COMMENT '维保商Id',
  `mpName` varchar(100) DEFAULT NULL COMMENT '维保商名称',
  `isOut` int(2) DEFAULT NULL COMMENT '是否外，0否1是',
  `orderId` int(11) DEFAULT NULL COMMENT '外派工单Id',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `defectId` (`defectId`),
  KEY `orgId` (`orgId`),
  KEY `status` (`status`)
) ENGINE=InnoDB AUTO_INCREMENT=2810840 DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='报修单操作最新记录表';



